# Config references:
# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
    # Examples
  - package-ecosystem: 'npm'
    directory: '/examples/basic'
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "weekly"
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: 'npm'
    directory: '/examples/complete'
    commit-message:
      prefix: chore
      include: scope
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "weekly"
