sudo: false

language: node_js

node_js:
  - 6.11.1 # LTS
  - 8 # Current

notifications:
  email:
    # Only send notifications when travis status changes
    on_failure: change
    on_success: change

cache:
  directories:
    - node_modules

branches:
  only:
    - master

script:
  - npm run lint
  - npm run test:cov
